### ISSUE TITLE
Infra provider not getting updated

### ISSUE THREAD

**Issue by vatsalparekh** [ManageIQ/manageiq-providers-kubevirt#38] opened 2018-03-05 10:46 UTC
After adding the `Openshift` provider with `kubevirt` for virtualization, I was able to see the infra provider, but that provider does not get refreshed like the container provider does. I've to manually do the refresh for the provider to fetch the data.
![screenshot from 2018-03-05 16-02-40](https://user-images.githubusercontent.com/6758282/36971050-8cca6be8-2090-11e8-8fc6-28e29e393e0f.png)

**Comment by pkliczewski** [comment] 2018-03-06 13:04
Can you please specify the steps to reproduce?

**Comment by vatsalparekh** [comment] 2018-03-07 08:07
With the solved issue #39 , I am seeing the VM and template info getting updated in the infra provider, but the field `Last Refresh` stays `Never`.

Steps:
- Add KubeVirt with Openshift as Container provider
- Check the Infra provider of Kubevirt

**Comment by jhernand** [comment] 2018-03-07 08:49
@pkliczewski note that this is a side effect of the refresh architecture of the provider. It doesn't use the traditional refresh mechanism used by other ManageIQ providers, so it never updates that "Last Refresh" field.

**Comment by pkliczewski** [comment] 2018-03-07 10:33
@jhernand Thanks. Looks like a gap we need to fix at some point. Needs to be investigated whether it is possible with our current code base.

**Comment by pkliczewski** [comment] 2018-06-04 08:54
PR fixing the issue was merged

**Closed by pkliczewski** 2018-06-04 08:54 UTC
